### ISSUE TITLE
GraphViz format

### ISSUE THREAD

**Issue by DJuego** [ArsMasiuk/qvge#53]
Hi and Happy New Year!!! First; Thank you for your tool! It looks great! 

I was looking for a tool like this and this could be a good candidate.

In principle, my interest is very basic. I want to visualize the [cpp-taskflow](https://github.com/cpp-taskflow/cpp-taskflow) diagrams in Graphivz format. For instance;

```
digraph Taskflow {
"A";
"A" -> "B";
"A" -> "C";
"B";
"B" -> "D";
"C";
"C" -> "D";
"D";
}
```
is it possible? Apparently the tool works with text documents but I can not export text file to valid graph files... I have tried to rename the file, but it is obvious i am a ignorant about graph files. :-(

Thanks!!

DJuego

**Comment by ArsMasiuk** [comment]
Hi! happy new year and thanks for your comments and for using this software!
Regarding your question, the app for now can export designed graphs into dot graphvis format. Did you mean this feature?

**Comment by DJuego** [comment]
Actually no. For instance;

 I have this input (Graphivz format):

```
// Taskflow with five tasks and six dependencies
digraph Taskflow {
  "A" -> "B"
  "A" -> "C"
  "A" -> "E"
  "B" -> "D"
  "B" -> "E"
  "C" -> "D"
}
```
and i want to generate this graph (output):

![image](https://user-images.githubusercontent.com/1956212/50609204-e7654d00-0ec6-11e9-9f8a-f77aea63bd5a.png)

This is the feature i need...

Thank you for your swift answer!

DJuego

**Comment by ArsMasiuk** [comment]
Ok, now I got it. You need an import feature. Currently this is not yet implemented, but I will think about it for the future releases.

**Comment by DJuego** [comment]
Thanks for your honest answer, @ArsMasiuk . You have my start. 👍  I will be attentive to future releases. Of course. :-) I like your philosophy (friendly, open source, crossplatform, liberal license, github, Qt. C++, etc, etc, etc...)

Meanwhile I will have to look for an alternative :-| Any suggestions would be welcome.

DJuego

**Comment by ArsMasiuk** [comment]
Thank you guys for this, I very appreciate your feedback.
Unfortunately the development progresses not so fast as I would like to do, because of the strong lacking of spare time. This project was initially a part of my Ph.D. work, but now it grew across the borders a little. So my plan is to build up a fully-functional but simple graph (and propably shape) editor in the future which could be an alternative for "big fat monsters" which are on the market now.

**Comment by ArsMasiuk** [comment]
Regarding to the question about alternative: why don't use the ui which comes together with graphvis tool? Yes, it is quite primitive, but as far as I know, you can pass into it any gv file and then select which layout engine to use. The output can be than drawn into png or something similar I guess.

**Comment by DJuego** [comment]
Yes. Yes. I will use that while I wait for a **Qt Visual Graph Editor** shiny release. Thanks @ArsMasiuk .

DJuego

**Comment by weed** [comment]
I was a PhD student in my young ages, but I couldn't complete the necessities. PhD is very hard work, you know. I wouldn't criticize you if you had to give up development of this software and had to concentrate on   your study. I hope you get good life.

**Comment by ArsMasiuk** [comment]
Yes, for me it wasn't easy, too. It took almost 15 years since start till finish (and I'm still waiting for some papers). I had to postpone working on my PhD thesis for some years because of work and family reasons (now my little boy is two years old).
The graph app implements some unique ideas of me (regarding ux and undo-redo stack for example). So I plan to go further with the development even if my PhD studio

**Comment by ArsMasiuk** [comment]
> I have this input (Graphivz format):
> ```
> and i want to generate this graph (output):
> ```
> DJuego

This will come with 0.5.2 release. Implemented via OGDF, so there is no much impact from my side to change the read & layout behavior. This means - the feauture should somehow work, but with no warranty at all...

**Comment by weed** [comment]
>I plan to go further with the development even if my PhD study is over.

Thank you for consideration of providing and developing the nice app after you completed your PhD course. In any case, while you are developing QVGA, I'll keep using the app and continue feedback, because I can use this app in any case, for example in application development, in designing my task procedure or even planing my busyness model. However, you don't have to try to be hero. That is your life.

By the way, indeed, I have two children, 10 years old daughter and 4 years old son. Our circumstances might be a little similar. I imagine that it might be very hard to do both study in PhD course and taking care of your family and your job. I hope your future would be fine.

**Comment by DJuego** [comment]
Thank you for this! "A journey of a thousand miles begins with one first step". 

I only miss the portable distribution. :-)

DJuego

**Comment by ArsMasiuk** [comment]
does dot import work for your dot files? can I close this ticket?
portable distribution is on the plan already.

**Comment by DJuego** [comment]
Well. I have the text:
```
digraph Taskflow {
  "A" -> "B"
  "A" -> "C"
  "A" -> "E"
  "B" -> "D"
  "B" -> "E"
  "C" -> "D"
}
```
I save the text in a .dot file. I open the file with Qt Visual Grapth Editor 0.5.2.
I get (with the shiny Sugiyama Layout) :

![image](https://user-images.githubusercontent.com/1956212/51074013-32265800-1671-11e9-9b0a-8b46fd7f902d.png)

I would say it is correct! :-D 👍  

Of course it has to be tested with more complex graphs. 

I am more used to the aesthetics of nodes as circles, but it is a minor detail. Or is it possible to modify it already with the editor?

Thanks again!

DJuego

**Comment by ArsMasiuk** [comment]
Sure, you can edit the shapes & colors of the items. just select them and use the right panel to change the properties.

**Comment by DJuego** [comment]
Now I understand. I missed the step of making the **selection** to apply the properties. xDD
The brackets can not be omitted, right?

DJuego

**Comment by DJuego** [comment]
:-)  Thank for your explanation about brackets.

Do you mind if I create a new issue to remember the save-only-topology (or strip-attributes) flag you mention? I think we can close this issue!

DJuego

**Comment by ArsMasiuk** [comment]
Yes, please open a new ticket, and this one could be closed.
