### ISSUE TITLE
Implement scroll during selection

### ISSUE THREAD

**Issue by ArsMasiuk** [ArsMasiuk/qvge#56]
Can be quite hard to realize...

**Comment by ArsMasiuk** [comment]
Yes, that would be also useful. The problem here is that there is a bug in qt which blocks such a behavior so it's like to be implemented from the scratch. So it would be custom selection and moving mechanisms anyway...

**Comment by weed** [comment]
Is the bug supposed to be fixed in the future?

**Comment by ArsMasiuk** [comment]
Well, I can't say if it will be fixed by qt team because they got more focused on the qml crap instead of correcting the actual issues. So I wouldn't be waiting for an "official" fix and would provide my own solution sometimes.

**Comment by weed** [comment]
How about the right button click to drag canvas? While you select some objects, you can drag canvas.

**Comment by ArsMasiuk** [comment]
Right click drag should be working already.

**Comment by weed** [comment]
It’s been a while. I felt that the startup window had become nicer since I don't have to find the editing file. By the way, I meant that you can start dragging canvas from right dragging at a point **outside** of selected objects. However, I'm not sure that this is a good way.

![_ g__my drive_office_190331_2019 1 6 holomagnet5 _2019 1 7 10 24 holomagnet5 xgr - qt visual graph editor 0 5 3 64bit 2019-03-04 13 27 57](https://user-images.githubusercontent.com/129954/53710675-cba80400-3e81-11e9-98e8-173a9b7a5289.png)

**Comment by ArsMasiuk** [comment]
Do you mean that the selection should remain during the drag?
Actually it is a good point because it will allow to expand the actual selection by items which were not visible before the canvas has been dragged...

**Comment by tatsuro-ueda** [comment]
>do you mean that the selection should remain during the drag after right click?

Yes, but this seems a bit strange operation. This is my only idea to drag objects to far place. Maybe there is better way.

**Comment by ArsMasiuk** [comment]
done in branch
